mutils:
  functions:  - file
  file:    local: false
    server-list:    - http://192.168.1.7:7749/
server:  port: 3333
  
spring: 
  servlet: 
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB