mutils:
  functions:
  - wechat-app
  - wechat-miniprogram
  - wechatpay-core
  - alipay
  wechat-app: 
    app-secret: 072382f74b1a61c308b8c0698f48dde2
    appid: wx6a2d7efb9cc709a6
  wechat-mini-program:
    app-secret: 990b3bb5ab08112981a34fa85c5638f2
    appid: wxd3f76b66d3435830
  wechat-pay-core:
    notify-url: http://www.daoting.org:15001/mafruits/recharge/alipayNotify
    partner-id: 1483596882
    partner-key: 792278faa874bf4cccc5c89c4622a66d
    with-refund: false
  alipay: 
    public-key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDDI6d306Q8fIfCOaTXyiUeJHkrIvYISRcc73s3vF1ZT7XN8RNPwJxo8pWaJMmvyTn9N4HQ632qJBVHf8sxHi/fEsraprwCtzvzQETrNRwVxLO5jVmRGi60j8Ue1efIlzPXV9je9mkjzOmdssymZkh2QhUrCmZYI/FCEa3/cNMW0QIDAQAB
    private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCljTAoWzzeRmsI5lWVAph4R+Ntw4efHHuMNFbE3tLtBJwj3sYsG2IaxqZ83QvDc2e9A5Qlk9JpEV8iwp4bQMitzwsRIZWSaM2Jy2qzJH94S8n86uxgTAiequDrSn0JIbT9T5KPNV91rw2JhyRxGA7FU4sgtS69zhmIJhhQwAyFzzl9H4ugEvNhY+IN3ZggE327e4RsVL2hYIsu/WyVX12B9xDypyNA1Y30P9yOcTyvnq1KQg44m9lqoloEn7wEIValP9KeZDWKmNlEIAiQFTZ2j+3L1lFXKum0AxaudLL4KKZ+xaMs/6uwSaSuOW2kC2haXyblTCWHO/CCK1FKEqWzAgMBAAECggEAKGmEvfU3sJLEAhIoBg3yJjp2PA8lBiQvzJPiMoCqQI2FiAQToCS3GA4yCfzzqCx9wFglS97/2AITlSqo6cIwuqz16KKoHmtS8TYkv8JDE5x8nC7EsOUenYzdBtLSHu6JfeR0xFylBtdKmK3SqYDT6jtwlPVliZPMC74w5VVcOTVuBiIAmz6NR1nDPUF3J++6yU9lJ21AILz21kLcEMSq3HyB20i5EG1mDCPc9Hi+owsNtqdpmx+iuYnmUgM72zHx9gQTQ+UgH4NnPDCd5UtaLSFZefOG1bMvIPmsk1EAPmCbj+xqj+r1ILkIsAlVHAQd5LQkexb+OIng20EuQ/k5IQKBgQDaZETRnumEEdysacBdVAc/vQEEv5sRdMvcSOiVWrM6lzH147W1ye/Gt3+zTTeFsO7OIqy4oxFKamJFGVMKNi1zaVyQt6VZPY5DTW+464Yf6HfwuHR8lw8kDsjWCCzvxY5u3ih0zmpiIzEyOUdEK1D9SCDFBWCof8T7KO6atson2QKBgQDCD3oQCxi4aMtuwH2OHPCUQpy0HbmVa2MdpR4+o9uasIhjfJyMI0u0EwTS/6dwVVvZXdgXKvKzuQgLgujgTKjiPhA8C4s84Piu/0zXX4nQ3+dNADpLJUXYE8GrLMzHNUbxoEtW0TJ5ZvnkiLEs8D5XFm+FgeaJ7ywL9RBlM+MuawKBgQCDJ4Bk2yimFgwOxxutcM9BqgI4ldFMtHXRfz+eom/Mmgx4/R2dZP7Iul7IkXDsqwtfZFeSMuwpYqZNlR3Xnh3Bl97tUjzM0TjkllaoGVndQ8D0IfJi+F0xbGeUkihafqxBTM3DCEu/UB81aEyyVck3st9rMwWPa9wicbyJ0YiqUQKBgQC/pzFRruPXHAftdUWKmKIwiijg6YpjOw9EM9JO4tz7ROUt+99Pt3wId9AH4lym4GY5oijLmKrhPBfp5nu/KXaRGeJGqs/0a+quSYzGF6CwHLD+pv7rQABeigR23WPQSZmrADfnoetLYpvhS+5PB2VJ9Opm3AemqgLCPGDY0gnHyQKBgQCIPCWLoW4nSI+S8UYKPPSkQmi5Rnpjxi+Pgvd8pImUqUDhoS1A34bMFQa8xieVJ6bCv7KBWhPZBr6bKPUj8hbK+Icfff4G3xZovqPZu+e6SoOxny407q1eV4Mbp2Z3+nKY1JtUvONsZ3Fe+rRpRxLk4uVaslYyKqU2FXXdSY6Z8A==
    appid: 2018122062678051
    notify-url: http://www.daoting.org:15001/mafruits/recharge/alipayNotify
    return-url: http://www.daoting.org:15001/mafruits/recharge/alipayNotify
    
server:  port: 3333
  
spring: 
  servlet: 
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB