mutils:
  functions:
  - wechat-app
  - wechat-miniprogram
  - wechatpay-core
  - alipay
  - file

  file:
    save-disk: D:/upload/
    server-url: http://192.168.1.7:3333/
    local-mapping: test
server:   port: 3333
  
spring: 
  servlet: 
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB