mutils:
  functions:
  - excel
  - wechat-app
  - wechat-jsapi
  - file
  excel:
    error-template-cell-index: 0
    error-template-path: E://error.xlsx
    error-template-row-index: 0
    error-template-export-name: 我是错的
    error-template-sheet-index: 23234
  wechat-app:
    appid: 
  file:
    local: false
    server-list:
    - http://192.168.1.7/
    
server:  port: 3333
  
spring: 
  servlet: 
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 1024MB